# Docker
jobs:
- job: Docker_Build_and_Push
  displayName: 'Build and push Docker image'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    displayName: 'Build and push an image to container registry'
    inputs:
      containerRegistry: 'docker777'
      repository: 'pasindu1952/melody-synthesis'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.BuildId)'